# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.define "web-bl-app" do |webblapp|
    webblapp.vm.box = "ubuntu/trusty64"

    webblapp.vm.hostname = "web-bl-app"

    webblapp.vm.synced_folder "../../../", "/var/www/mpb"

    webblapp.vm.network "forwarded_port", guest: 8080, host: 8080
    webblapp.vm.network "private_network", ip: "192.168.33.10"

    webblapp.vm.provision "shell", :path => "provision.sh"
  end
end
