# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "web-bl-app" do |webblapp|
    webblapp.vm.box = "puppetlabs/centos-7.0-64-puppet"
    webblapp.vm.box_url = "https://atlas.hashicorp.com/puppetlabs/boxes/centos-7.0-64-puppet"
    webblapp.vm.hostname = "web-bl-app"

    webblapp.vm.synced_folder "../../../", "/var/www/mpb"

    webblapp.vm.network "forwarded_port", guest: 3000, host: 3000
    webblapp.vm.network "private_network", ip: "192.168.33.10"

    webblapp.vm.provision "shell", :path => "provision.sh"
  end
end
